spring:
  datasource:
    url: jdbc:h2:mem:test_mem
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none